### PR TITLE
Add limited player vision demo

### PR DESCRIPTION
**Pull request by azagaya**
This PR adds the basic example.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Please let me know when it's ready to review and merge

**Comment by NathanLovato** [comment]
Note you have write access now. Moving forward, you can make branches on this repository so a teammate or I can directly update the PR and put the code review / refactor as a commit directly. It'll be more efficient and convenient for the both of us.

**Comment by azagaya** [comment]
Hi! i just wanted to put a background other than a solid color before merging, but i've been really busy today.
Ok, in the future i will make a branch and merge directly there.

**Comment by azagaya** [comment]
Closing this as i added a new branch called limited-vision-demo, already merged.

**Pull request closed without merging**
