### PR TITLE
Four SideScrolling Movements implemented

### PR DESCRIPTION
**Pull request by raformatico**
You can select the movement to test pressing the correponding number in the main scene execution:
(1) Space Shooter like level
(2) Flappy Bird like movement
(3) Angry Bird Catapult like movement
(4) Geometry Dash like movement

**Please check if the PR fulfills these requirements:**

- [ ] The commit message follows our guidelines.
- For bug fixes and features:
    - [ ] You tested the changes.
    - [ ] You updated the docs or changelog.

Related issue (if applicable): #

**What kind of change does this PR introduce?**

**Does this PR introduce a breaking change?**

## New feature or change ##

**What is the current behavior?** 

**What is the new behavior?**

**Other information**
It's important to note that there is additional code to change easily between movements which I don't think we need to include or explain in the written tut.

### CODE REVIEW

**Comment by NathanLovato** [comment]
Here are some issues I see:

1. In the space level, the character flickers. I tried setting the camera to move on physics process but it didn't help. That needs to be fixed for a tutorial.
2. Movement generally feels slow and floaty, especially in the angry birds, geometry dash, and platformer demos. That's a matter of tweaking some values. I can do this if you'd like.

Typically, games like space shooters and flappy bird work by moving the background and the enemies rather than the player and camera. I don't know if it's great to teach, I'm unsure of the shortcomings, except for the camera flickering in the space shooter's case.

@Razoric480, Rafael's working on basic side-scroll movement demos. In the space-shooter and flappy bird ones, what do you think of keeping the character in-place and moving the environment vs moving the character + camera?

Screenshot from 2021-01-05 07-52-20

**Comment by NathanLovato** [comment]
For the camera flicker, I would:

1. Have the player's root node not be the kinematic body, but something else that moves continuously forward, with the collision shapes you used.
2. Have both the camera and the kinematic body as a child of it.
3. Then have the player kinematic body move relative to its parent.

I'm unsure this would fix the problem but it might, and that's what i'd try at least.

**Comment by Razoric480** [comment]
@NathanLovato Depends for how long the game goes for. If it's a finite level and you have control over its size, then there's not really going to be that big a difference - nothing really noticeable whether it's the character or the world moving.

However, in an infinite runner, things change. For short stints of play, you can probably get away with it there as well. However, as you start to increase the number of pixels/units, there is going to be a certain amount of precision loss with the floating point numbers, and the floating point "error" can build up.

Mind, it can take quite a while before that issue is ever reached, depending on how fast you go anyway , but it's something to keep in mind.

It also simplifies being able to move left/right without adjusting the speed at which you traverse the infinite data, since you have a small finite space (the game window) in which you can move. It just so happens that the world is moving too, which is what creates the scrolling data.

**Comment by raformatico** [comment]
@Razoric480 could you explain with an example or with some more detail? Because I can't really understand this floating point problem.

@NathanLovato  I'm going to try:
1.- The adjustments you propose for the camera flicker
2.- Improve the feeling about angry birds, geometry dash, and platformer demos.

**Comment by Razoric480** [comment]
@raformatico As more and more bits of the X component of the position's Vector2 are taken up, you begin to lose precision. Only so many of the bits are available, and they have to be split between base and decimal points. As the base grows into a bigger number, there are fewer of them available for the decimal part.

So think of it this way: if you are at units 1000000.0 and you want to move to unit 1000000.0001, you may find the number rounding in ways that are undesirable, which can result in jitter. At 10 million, 100 million, 1 billion and beyond, the problem becomes more and more obvious.

It could get so bad that the player just can't dodge an obstacle because the game just didn't have the space to store that precise a decimal number and it rounded their position closer to an obstacle instead of away.

If you want a big example of floating point precision breaking down, you can research Minecraft's Farlands, or how physics breaks down beyond the world border.

If the world moves instead of the player, then all the relevant and important action happens inside of a 0..1920 area, which leaves plenty of bits to hold the decimal points.

Mind, it can take a while for the problem to become obvious, or problematic, and only a subset of players would be so dedicated to reaching millions to billions of units away from the origin point. But that it can happen is something you need to keep in mind when designing a game on a technical level.

**Comment by NathanLovato** [comment]
And for having designed infinite games, you'd be surprised, we've had players player for 1 hour straight without losing in a Canabalt clone. It was the background spawning and moving around the character so no problem, but with that duration you'd start having bugs.

Nothing too important with this demo though.

**Comment by raformatico** [comment]
Thanks for the explanation, it's a lot more clear now!

I think I'm not bad at taking into account this type of "weird/unexpected" behavior when I'm developing. But I've realized that it's hard to me to take this into account, as it's a variable (or a whole process) which is working inside the engine (and I'm not aware of it).  

@NathanLovato I'm not sure if the flickering issue is still there... Could you confirm it?

**Comment by NathanLovato** [comment]
> But I've realized that it's hard to me to take this into account, as it's a variable (or a whole process) which is working inside the engine

That's part of the challenge in game development, there's a lot you need to learn regarding what's happening under the hood to avoid problems in practice. Don't worry too much, we're here to help with that.

**Comment by NathanLovato** [comment]
Yes, the character's was still flickering, but it's normal: you move the camera with _process() while the character updates on physics callbacks. Normal processing (_process()) and physics processing (_physics_process()) happen out of sync, and at different rates. I hadn't paid attention to that in the previous iteration, I'll patch the code right away.

**Comment by NathanLovato** [comment]
Done, all good!

**Comment by raformatico** [comment]
Perfect! I'll send you the outline and the comments about [writing style guide](https://www.gdquest.com/docs/guidelines/best-practices/writing/) if there is any.

**Comment by NathanLovato** [comment]
Thanks!

**Pull request merged**
